/**
 * generate-index.js
 * ------------------
 * EditGalaxy (surajfx.in) - Static Data Embedding Script
 *
 * Ei script ta Firebase Realtime Database-er 'templates' ar 'prompts'
 * path theke SOB data fetch kore, tarpor index.html-er bhitore
 * SORASORI bosiye dei (window.__PRELOADED_DATA__ = {templates, prompts}).
 *
 * Result: User jokhon site khule, browser-ke r Firebase-e kono
 * request pathiye wait korte hoy na first render-er jonno.
 * Data already HTML-er bhitore thake -> ZERO loading gap.
 *
 * Kivabe run korbe:
 *   1. npm install firebase-admin
 *   2. serviceAccountKey.json ei folder-e rakhbo
 *      (template-cc1cb Firebase project-er Service Account key)
 *   3. Terminal-e: node generate-index.js
 *   4. index.html nijei update hoye jabe notun data diye
 */

const admin = require("firebase-admin");
const fs = require("fs");
const path = require("path");

const serviceAccount = require("./serviceAccountKey.json");
if (!admin.apps.length) {
  admin.initializeApp({
    credential: admin.credential.cert(serviceAccount),
    databaseURL: "https://template-cc1cb-default-rtdb.firebaseio.com",
  });
}

const db = admin.database();
const INDEX_PATH = path.join(__dirname, "index.html");

const START_MARKER = "<!-- PRELOADED_DATA_START (auto-generated by generate-index.js, do not edit by hand) -->";
const END_MARKER = "<!-- PRELOADED_DATA_END -->";

async function generate() {
  console.log("Firebase theke templates ar prompts fetch kora hocche...");

  const [templatesSnap, promptsSnap] = await Promise.all([
    db.ref("templates").once("value"),
    db.ref("prompts").once("value"),
  ]);

  const templatesData = templatesSnap.val() || {};
  const promptsData = promptsSnap.val() || {};

  const templates = Object.entries(templatesData).map(([id, x]) => ({ id, ...x }));
  const prompts = Object.entries(promptsData).map(([id, x]) => ({ id, ...x }));

  console.log(`${templates.length} ta template, ${prompts.length} ta prompt paoa gelo.`);

  if (!fs.existsSync(INDEX_PATH)) {
    console.error("index.html paoa jayni! Ei script ta index.html-er pashe rakha ache to?");
    process.exit(1);
  }

  let html = fs.readFileSync(INDEX_PATH, "utf-8");

  const startIdx = html.indexOf(START_MARKER);
  const endIdx = html.indexOf(END_MARKER);

  if (startIdx === -1 || endIdx === -1) {
    console.error("index.html-e PRELOADED_DATA marker paoa jayni. Script cholbe na.");
    console.error("Nishchit korun index.html-e ei duita comment line ache:");
    console.error(START_MARKER);
    console.error(END_MARKER);
    process.exit(1);
  }

  const payload = { templates, prompts };
  const safeJson = JSON.stringify(payload).replace(/</g, "\\u003c");

  const replacement =
    START_MARKER +
    `\n<script>window.__PRELOADED_DATA__ = ${safeJson};</script>\n` +
    END_MARKER;

  const before = html.slice(0, startIdx);
  const after = html.slice(endIdx + END_MARKER.length);
  const newHtml = before + replacement + after;

  fs.writeFileSync(INDEX_PATH, newHtml, "utf-8");
  console.log(`index.html update hoye gelo (${templates.length} template + ${prompts.length} prompt embed kora holo).`);

  // Firebase Admin SDK background-e connection khola rakhe, tai script-ta
  // nijei bondho na hoye "hanging" thake. Explicitly exit kore dei.
  process.exit(0);
}

generate().catch((err) => {
  console.error("Error hoise:", err);
  process.exit(1);
});

